# Generated by Django 4.0.4 on 2022-05-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email de contacto'),
        ),
    ]
