# Generated by Django 4.0.4 on 2022-05-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodel',
            options={'ordering': ['title'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
